---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    app: toolbox
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
    - name: toolbox
      image: jacobmammoliti/toolbox
      ports:
        - containerPort: 8080
      command: [ "sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  serviceAccount: toolbox