---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: facts-api-frontend
          hosts: ['34.28.206.162', '20.75.160.128', '35.224.210.156']